#!/bin/bash
# A Simple TODOs management.

# Copyright (C) 2019 Andres Chamorro.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

version="todo 0.1 - (C) 2019 Andres Chamorro
Released under the GNU GPL.
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <https://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law."

usage="Usage: $0 [OPTIONS] [TEXT]
A Simple TODOs management.
 OPTIONS
  -a --add     Adds a new todo task 
  -d --delete  Delete task in line
  -v --verbose Show current todo task
  -h --help    Display this help and exit"

while (( "$#" )); do
  case "$1" in
		-h|--help)
			printf '%s\n\n' "$version"
			printf '%s\n\n' "$usage"
      exit
			;;
    -a|--add)
			echo " ⇾ $2" >> $TODO;
      shift 2
      ;;
    -d|--delete)
			sed -i -e "$2d" $TODO;
      shift 2
      ;;
    -v|--verbose)
			lnum=1
			while IFS= read -r line; do
				printf '%s%s\n' "$lnum" "$line";
				((lnum++));
			done <"$TODO"
      shift
      ;;
    --) # end argument parsing
      shift
      break
      ;;
    -*|--*=) # unsupported flags
      echo "Error: Unsupported flag $1" >&2
      exit 1
      ;;
    *) # preserve positional arguments
      shift
      ;;
  esac
done
